---

- name: ghost
  docker:
    name: ghost
    state: started
    image: ghost
    volumes:
      - "/usr/local/ghost:/var/lib/ghost"
    ports:
      - "2368:2368"

# - name: install ghostium theme
#   git: repo=https://github.com/oswaldoacauan/ghostium/ dest=/usr/local/ghost/content/themes/ghostium
#   tags:
#     - ghost
#     - ghostium

# - name: install ghostwriter theme
#   git: repo=https://github.com/roryg/ghostwriter.git dest=/usr/local/ghost/content/themes/ghostwriter
#   tags:
#     - ghost
#     - ghostwriter

# - name: install GhostScroll theme
#   git: repo=https://github.com/grmmph/GhostScroll.git dest=/usr/local/ghost/content/themes/GhostScroll
#   tags:
#     - ghost
#     - GhostScroll

